"""NQ-025: itinerary persistence

Revision ID: 1047dcaaace4
Revises: d8ddbda0979e
Create Date: 2026-09-09 00:00:26.559260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1047dcaaace4'
down_revision: Union[str, Sequence[str], None] = 'd8ddbda0979e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tripspecs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tripspecs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tripspecs_payload', 'tripspecs', ['payload'], unique=False, postgresql_using='gin', postgresql_ops={'payload': 'jsonb_path_ops'})
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tripspec_id', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('draft','active','completed','abandoned')", name='ck_itinerary_status'),
    sa.ForeignKeyConstraint(['tripspec_id'], ['tripspecs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('total_cost_inr', sa.Integer(), nullable=False),
    sa.Column('total_duration_min', sa.Integer(), nullable=False),
    sa.Column('total_walk_m', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('validator_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'version_no', name='uq_version_no')
    )
    op.create_table('itinerary_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('arrive_min', sa.SmallInteger(), nullable=False),
    sa.Column('depart_min', sa.SmallInteger(), nullable=False),
    sa.Column('visit_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('cost_inr', sa.Integer(), nullable=False),
    sa.Column('mode_from_prev', sa.String(length=20), nullable=True),
    sa.Column('travel_seconds_from_prev', sa.Integer(), nullable=True),
    sa.Column('travel_distance_m_from_prev', sa.Integer(), nullable=True),
    sa.Column('walk_m_from_prev', sa.Integer(), nullable=True),
    sa.Column('leg_cost_inr', sa.Integer(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['itinerary_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'seq', name='uq_stop_seq')
    )
    op.create_table('plan_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tripspec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_poi_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optimizer_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optimizer_status', sa.String(length=20), nullable=False),
    sa.Column('solve_ms', sa.Integer(), nullable=True),
    sa.Column('weather', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feasibility_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['itinerary_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_snapshots')
    op.drop_table('itinerary_stops')
    op.drop_table('itinerary_versions')
    op.drop_table('itineraries')
    op.drop_index('ix_tripspecs_payload', table_name='tripspecs', postgresql_using='gin', postgresql_ops={'payload': 'jsonb_path_ops'})
    op.drop_table('tripspecs')
    # ### end Alembic commands ###
