"""POI photo credit columns

Revision ID: 2bb6d252a09d
Revises: d657b263c8af
Create Date: 2026-09-22 00:57:37.652996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb6d252a09d'
down_revision: Union[str, Sequence[str], None] = 'd657b263c8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pois', sa.Column('image_credit', sa.Text(), nullable=True))
    op.add_column('pois', sa.Column('image_license', sa.String(length=40), nullable=True))
    op.add_column('pois', sa.Column('image_source_url', sa.Text(), nullable=True))
    op.add_column('pois', sa.Column('wikidata_sitelinks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'wikidata_sitelinks')
    op.drop_column('pois', 'image_source_url')
    op.drop_column('pois', 'image_license')
    op.drop_column('pois', 'image_credit')
    # ### end Alembic commands ###
