"""NQ-025: objective_value as integer

Revision ID: 7886a04d8931
Revises: 1047dcaaace4
Create Date: 2026-09-09 09:49:56.175056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7886a04d8931'
down_revision: Union[str, Sequence[str], None] = '1047dcaaace4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_versions', sa.Column('objective_value', sa.Integer(), nullable=True))
    op.drop_column('itinerary_versions', 'quality_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_versions', sa.Column('quality_score', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.drop_column('itinerary_versions', 'objective_value')
    # ### end Alembic commands ###
