"""NQ-011b: place gazetteer

Revision ID: a95eba6f3f2c
Revises: 7886a04d8931
Create Date: 2026-09-19 22:46:19.352456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'a95eba6f3f2c'
down_revision: Union[str, Sequence[str], None] = '7886a04d8931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('wikidata_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_ref', name='uq_places_source_ref')
    )
    op.create_index('ix_places_kind', 'places', ['kind'], unique=False)
    op.create_index('ix_places_name_trgm', 'places', ['name_normalized'], unique=False, postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_places_name_trgm', table_name='places', postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.drop_index('ix_places_kind', table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###

