"""v2: exploration schema - 90 km envelope, taxonomy v2, recommendations,
knowledge corpus, conversations, versioned plans, auth tokens, traces.

Hand-written, not autogenerated: every existing row is carried forward.

  * poi_categories are remapped from the v1 keys to the v2 taxonomy
    (ADR-024) and POIs/links follow; obsolete v1 categories are removed only
    after nothing references them.
  * POIs gain geography (distance from the configured centre, region bucket),
    ranges for duration/cost with an honest confidence, tags, suitability and
    attribution. Old columns are backfilled into the new ones, then dropped.
    Rows outside the 90 km envelope are kept but deactivated
    (region_bucket = 'OUT_OF_SCOPE').
  * Itineraries created before ownership existed get session_id
    'legacy-unowned' so the new owner constraint holds without deleting them.

Revision ID: b21e4c7a9f30
Revises: 7886a04d8931
Create Date: 2026-09-21
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import geoalchemy2
from pgvector.sqlalchemy import Vector

revision: str = "b21e4c7a9f30"
down_revision: Union[str, Sequence[str], None] = "7886a04d8931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Frozen copy of data/config/categories.yaml at the time of this migration.
# Migrations must not read live config: a later edit to the YAML would
# otherwise change what an old migration does.
#   key: (display, group, io, visit_min, visit_typ, visit_max, cost_min, cost_typ, cost_max, meal, theme)
V2_CATEGORIES = {
    "park": ("Park", "nature", "outdoor", 30, 60, 120, 0, 0, 50, False, False),
    "garden": ("Garden", "nature", "outdoor", 45, 75, 150, 0, 30, 100, False, False),
    "lake": ("Lake", "nature", "outdoor", 30, 60, 120, 0, 0, 50, False, False),
    "nature": ("Nature reserve", "nature", "outdoor", 60, 150, 300, 0, 100, 500, False, False),
    "hill": ("Hill", "nature", "outdoor", 90, 180, 360, 0, 50, 300, False, False),
    "viewpoint": ("Viewpoint", "nature", "outdoor", 20, 45, 90, 0, 0, 50, False, False),
    "forest": ("Forest", "nature", "outdoor", 60, 120, 240, 0, 0, 200, False, False),
    "waterfall": ("Waterfall", "nature", "outdoor", 45, 90, 180, 0, 30, 100, False, False),
    "reservoir": ("Reservoir", "nature", "outdoor", 45, 90, 180, 0, 0, 50, False, False),
    "museum": ("Museum", "culture", "indoor", 45, 90, 150, 0, 50, 300, False, False),
    "gallery": ("Art gallery", "culture", "indoor", 30, 60, 120, 0, 0, 200, False, False),
    "science": ("Science centre", "culture", "indoor", 60, 120, 180, 50, 100, 300, False, False),
    "history": ("Historic site", "culture", "outdoor", 20, 45, 90, 0, 0, 50, False, False),
    "heritage": ("Heritage site", "culture", "mixed", 30, 60, 120, 0, 20, 100, False, False),
    "palace": ("Palace", "culture", "mixed", 45, 90, 150, 0, 200, 600, False, False),
    "fort": ("Fort", "culture", "outdoor", 45, 90, 180, 0, 25, 100, False, False),
    "monument": ("Monument", "culture", "outdoor", 15, 30, 60, 0, 0, 50, False, False),
    "architecture": ("Architecture", "culture", "outdoor", 15, 30, 60, 0, 0, 0, False, False),
    "temple": ("Temple", "spiritual", "mixed", 20, 45, 90, 0, 0, 100, False, False),
    "church": ("Church", "spiritual", "indoor", 15, 30, 60, 0, 0, 0, False, False),
    "mosque": ("Mosque", "spiritual", "indoor", 15, 30, 60, 0, 0, 0, False, False),
    "religious_site": ("Religious site", "spiritual", "mixed", 20, 40, 90, 0, 0, 0, False, False),
    "cafe": ("Cafe", "food", "indoor", 30, 60, 120, 150, 300, 600, True, False),
    "restaurant": ("Restaurant", "food", "indoor", 45, 75, 120, 200, 500, 1500, True, False),
    "street_food": ("Street food", "food", "outdoor", 15, 30, 60, 50, 150, 300, True, False),
    "dessert": ("Dessert", "food", "indoor", 15, 30, 45, 80, 200, 400, False, False),
    "shopping": ("Shopping", "shopping", "indoor", 30, 60, 150, 0, 0, 0, False, False),
    "market": ("Market", "shopping", "outdoor", 30, 60, 120, 0, 0, 0, False, False),
    "mall": ("Mall", "shopping", "indoor", 60, 120, 240, 0, 0, 0, False, False),
    "entertainment": ("Entertainment", "fun", "indoor", 90, 150, 240, 200, 400, 1500, False, False),
    "gaming": ("Gaming", "fun", "indoor", 60, 90, 150, 300, 600, 1200, False, False),
    "activity": ("Activity", "fun", "mixed", 60, 90, 180, 300, 700, 1500, False, False),
    "adventure": ("Adventure", "fun", "outdoor", 120, 180, 360, 500, 1500, 3000, False, False),
    "nightlife": ("Nightlife", "fun", "indoor", 90, 150, 240, 500, 1200, 3000, False, False),
    "farm": ("Farm", "experience", "outdoor", 90, 180, 360, 0, 500, 2000, False, False),
    "experience": ("Experience", "experience", "mixed", 60, 120, 240, 300, 800, 2500, False, False),
    "workshop": ("Workshop", "experience", "indoor", 90, 150, 240, 500, 1200, 2500, False, False),
    "photography": ("Photography", "theme", "mixed", 30, 60, 120, 0, 0, 0, False, True),
    "romantic": ("Romantic", "theme", "mixed", 30, 60, 120, 0, 0, 0, False, True),
    "family": ("Family", "theme", "mixed", 30, 60, 120, 0, 0, 0, False, True),
    "kids": ("Kids", "theme", "mixed", 30, 60, 120, 0, 0, 0, False, True),
    "neighborhood": ("Neighbourhood", "explore", "outdoor", 60, 120, 180, 0, 0, 0, False, False),
    "walking_area": ("Walking area", "explore", "outdoor", 30, 60, 120, 0, 0, 0, False, False),
    "other": ("Other", "other", "mixed", 30, 60, 120, 0, 0, 0, False, False),
}

# v1 key -> v2 key. Keys equal in both versions are omitted.
V1_TO_V2 = {
    "bar": "nightlife",
    "historical": "history",
    "art_gallery": "gallery",
    "sunset": "viewpoint",
    "bookstore": "shopping",
    "landmark": "monument",
}

# Frozen centre and radius (settings defaults at the time of this migration).
CENTER_LON, CENTER_LAT, RADIUS_KM = 77.5946, 12.9716, 90.0

REGION_BUCKETS = "('CITY_CORE','CITY','OUTSKIRTS','NEARBY_ESCAPE')"
INTERACTION_ACTIONS = ("('view','click','save','unsave','dismiss','add_to_plan',"
                       "'remove_from_plan','show_similar','tell_me_more','mark_visited','shown')")


def _arr(name, nullable=False):
    return sa.Column(name, postgresql.ARRAY(sa.Text()), nullable=nullable,
                     server_default=sa.text("'{}'::text[]"))


def upgrade() -> None:
    for ext in ("postgis", "pg_trgm", "unaccent", "vector"):
        op.execute(f"CREATE EXTENSION IF NOT EXISTS {ext}")

    # ------------------------------------------------------------------ user
    op.add_column("user", sa.Column("display_name", sa.String(80), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(timezone=True),
                                    server_default=sa.text("now()"), nullable=True))

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("user.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])

    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("user.id", ondelete="CASCADE"),
                  primary_key=True),
        _arr("favorite_categories"), _arr("disliked_categories"), _arr("favorite_moods"),
        sa.Column("preferred_pace", sa.String(10)),
        sa.Column("typical_budget_inr", sa.Integer()),
        sa.Column("indoor_outdoor_preference", sa.String(10)),
        _arr("dietary_preferences"), _arr("party_preferences"), _arr("favorite_areas"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.CheckConstraint("preferred_pace IS NULL OR preferred_pace IN "
                           "('quick','balanced','relaxed')", name="ck_pref_pace"),
        sa.CheckConstraint("typical_budget_inr IS NULL OR typical_budget_inr >= 0",
                           name="ck_pref_budget"),
        sa.CheckConstraint("indoor_outdoor_preference IS NULL OR "
                           "indoor_outdoor_preference IN ('indoor','outdoor','any')",
                           name="ck_pref_io"),
    )

    # --------------------------------------------------------- categories v2
    op.add_column("poi_categories", sa.Column("group_key", sa.String(20),
                                              server_default="other", nullable=False))
    op.add_column("poi_categories", sa.Column("indoor_outdoor", sa.String(10),
                                              server_default="mixed", nullable=False))
    for col, default in (("visit_min", 30), ("visit_max", 120), ("cost_min", 0), ("cost_max", 0)):
        op.add_column("poi_categories", sa.Column(col, sa.Integer(),
                                                  server_default=str(default), nullable=False))
    op.add_column("poi_categories", sa.Column("is_theme", sa.Boolean(),
                                              server_default=sa.false(), nullable=False))

    conn = op.get_bind()
    next_id = conn.execute(sa.text("SELECT COALESCE(MAX(id), 0) FROM poi_categories")).scalar()
    for key, (name, grp, io, vmin, vtyp, vmax, cmin, ctyp, cmax, meal, theme) in V2_CATEGORIES.items():
        exists = conn.execute(sa.text("SELECT id FROM poi_categories WHERE key = :k"),
                              {"k": key}).scalar()
        params = {"k": key, "n": name, "g": grp, "io": io, "vmin": vmin, "vtyp": vtyp,
                  "vmax": vmax, "cmin": cmin, "ctyp": ctyp, "cmax": cmax, "meal": meal,
                  "theme": theme, "indoor": io == "indoor",
                  "ws": io == "outdoor"}
        if exists:
            conn.execute(sa.text("""
                UPDATE poi_categories SET display_name=:n, group_key=:g, indoor_outdoor=:io,
                    default_visit_minutes=:vtyp, visit_min=:vmin, visit_max=:vmax,
                    typical_cost_inr=:ctyp, cost_min=:cmin, cost_max=:cmax,
                    meal_category=:meal, is_theme=:theme, is_indoor=:indoor,
                    weather_sensitive=:ws
                WHERE key=:k"""), params)
        else:
            next_id += 1
            conn.execute(sa.text("""
                INSERT INTO poi_categories (id, key, display_name, group_key, indoor_outdoor,
                    default_visit_minutes, visit_min, visit_max, is_indoor, weather_sensitive,
                    typical_cost_inr, cost_min, cost_max, meal_category, is_theme)
                VALUES (:id, :k, :n, :g, :io, :vtyp, :vmin, :vmax, :indoor, :ws,
                        :ctyp, :cmin, :cmax, :meal, :theme)"""), {**params, "id": next_id})

    for old, new in V1_TO_V2.items():
        params = {"old": old, "new": new}
        conn.execute(sa.text("""
            UPDATE pois SET primary_category = (SELECT id FROM poi_categories WHERE key=:new)
            WHERE primary_category = (SELECT id FROM poi_categories WHERE key=:old)"""), params)
        # Links: move to the new category unless the POI already links there.
        conn.execute(sa.text("""
            DELETE FROM poi_category_links l
            USING poi_categories o, poi_categories n
            WHERE o.key=:old AND n.key=:new AND l.category_id=o.id
              AND EXISTS (SELECT 1 FROM poi_category_links x
                          WHERE x.poi_id=l.poi_id AND x.category_id=n.id)"""), params)
        conn.execute(sa.text("""
            UPDATE poi_category_links SET category_id=(SELECT id FROM poi_categories WHERE key=:new)
            WHERE category_id=(SELECT id FROM poi_categories WHERE key=:old)"""), params)
        conn.execute(sa.text("DELETE FROM poi_categories WHERE key=:old"), params)
    op.execute("SELECT setval(pg_get_serial_sequence('poi_categories','id'), "
               "(SELECT MAX(id) FROM poi_categories), true)")

    # ------------------------------------------------------------------ pois
    new_cols = [
        sa.Column("slug", sa.String(160)),
        sa.Column("short_description", sa.Text()),
        sa.Column("description_source", sa.String(20)),
        sa.Column("distance_from_center_km", sa.Numeric(7, 3)),
        sa.Column("region_bucket", sa.String(20)),
        sa.Column("district", sa.String(80)),
        sa.Column("locality", sa.String(120)),
        sa.Column("neighborhood", sa.String(120)),
        _arr("experience_tags"), _arr("mood_tags"), _arr("food_tags"), _arr("dietary_tags"),
        _arr("activity_tags"), _arr("accessibility_tags"),
        sa.Column("indoor_outdoor", sa.String(10), server_default="unknown", nullable=False),
        sa.Column("weather_suitability", sa.String(20), server_default="all_weather",
                  nullable=False),
        sa.Column("opening_hours_raw", sa.Text()),
        sa.Column("opening_hours_confidence", sa.Numeric(3, 2), server_default="0",
                  nullable=False),
        sa.Column("visit_duration_min", sa.Integer()),
        sa.Column("visit_duration_typical", sa.Integer()),
        sa.Column("visit_duration_max", sa.Integer()),
        sa.Column("estimated_cost_min", sa.Integer(), server_default="0", nullable=False),
        sa.Column("estimated_cost_typical", sa.Integer(), server_default="0", nullable=False),
        sa.Column("estimated_cost_max", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_confidence", sa.String(20), server_default="category_default",
                  nullable=False),
        sa.Column("data_confidence", sa.Numeric(3, 2), server_default="0", nullable=False),
        sa.Column("recommendable", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("family_friendly", sa.Boolean()),
        sa.Column("kids_friendly", sa.Boolean()),
        sa.Column("senior_friendly", sa.Boolean()),
        sa.Column("couple_friendly", sa.Boolean()),
        sa.Column("solo_friendly", sa.Boolean()),
        sa.Column("group_friendly", sa.Boolean()),
        sa.Column("recommended_as_primary_destination", sa.Boolean(),
                  server_default=sa.false(), nullable=False),
        sa.Column("requires_large_time_block", sa.Boolean(), server_default=sa.false(),
                  nullable=False),
        sa.Column("short_escape", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("day_trip_suitable", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("is_chain", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("chain_key", sa.String(80)),
        sa.Column("wikipedia_title", sa.Text()),
        sa.Column("image_attribution", postgresql.JSONB()),
        _arr("source_urls"), _arr("source_names"),
        sa.Column("source_license", sa.String(160), server_default="ODbL-1.0", nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True)),
        sa.Column("search_text", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    ]
    for col in new_cols:
        op.add_column("pois", col)

    op.execute(f"""
        UPDATE pois p SET
            slug = 'poi-' || p.id,
            distance_from_center_km = round((ST_Distance(p.geom,
                ST_SetSRID(ST_MakePoint({CENTER_LON}, {CENTER_LAT}), 4326)::geography)
                / 1000.0)::numeric, 3),
            locality = p.area,
            indoor_outdoor = CASE WHEN p.indoor IS TRUE THEN 'indoor'
                                  WHEN p.indoor IS FALSE THEN 'outdoor'
                                  ELSE c.indoor_outdoor END,
            visit_duration_typical = COALESCE(p.visit_minutes, c.default_visit_minutes),
            visit_duration_min = LEAST(c.visit_min, COALESCE(p.visit_minutes, c.default_visit_minutes)),
            visit_duration_max = GREATEST(c.visit_max, COALESCE(p.visit_minutes, c.default_visit_minutes)),
            estimated_cost_typical = COALESCE(p.cost_estimate_inr, c.typical_cost_inr),
            estimated_cost_min = LEAST(c.cost_min, COALESCE(p.cost_estimate_inr, c.typical_cost_inr)),
            estimated_cost_max = GREATEST(c.cost_max, COALESCE(p.cost_estimate_inr, c.typical_cost_inr)),
            cost_confidence = CASE WHEN p.cost_estimate_inr IS NOT NULL THEN 'source_tag'
                                   ELSE 'category_default' END,
            opening_hours_raw = p.tags->>'opening_hours',
            opening_hours_confidence = COALESCE((SELECT MAX(h.confidence)
                FROM poi_opening_hours h WHERE h.poi_id = p.id), 0),
            source_names = ARRAY['OpenStreetMap'],
            source_urls = CASE WHEN p.source = 'osm'
                THEN ARRAY['https://www.openstreetmap.org/' || p.source_ref] ELSE '{{}}' END,
            search_text = p.name,
            data_confidence = 0.30,
            recommendable = (p.prominence >= 0.1 OR p.curated)
        FROM poi_categories c WHERE c.id = p.primary_category
    """)
    op.execute(f"""
        UPDATE pois SET region_bucket = CASE
            WHEN distance_from_center_km <= 15 THEN 'CITY_CORE'
            WHEN distance_from_center_km <= 30 THEN 'CITY'
            WHEN distance_from_center_km <= 60 THEN 'OUTSKIRTS'
            WHEN distance_from_center_km <= {RADIUS_KM} THEN 'NEARBY_ESCAPE'
            ELSE 'OUT_OF_SCOPE' END
    """)
    op.execute("UPDATE pois SET active = false, recommendable = false "
               "WHERE region_bucket = 'OUT_OF_SCOPE'")

    for col in ("slug", "distance_from_center_km", "region_bucket", "visit_duration_min",
                "visit_duration_typical", "visit_duration_max"):
        op.alter_column("pois", col, nullable=False)
    for col in ("visit_minutes", "cost_estimate_inr", "cost_basis", "indoor", "weather_flags",
                "area"):
        op.drop_column("pois", col)

    op.create_unique_constraint("uq_pois_slug", "pois", ["slug"])
    op.add_column("pois", sa.Column(
        "search_tsv", postgresql.TSVECTOR(),
        sa.Computed("to_tsvector('simple', search_text)", persisted=True)))
    op.create_check_constraint("ck_pois_quality", "pois",
                               "quality_score >= 0 AND quality_score <= 1")
    op.create_check_constraint("ck_pois_distance", "pois", "distance_from_center_km >= 0")
    op.create_check_constraint(
        "ck_pois_region", "pois",
        f"region_bucket IN {REGION_BUCKETS} OR (NOT active AND region_bucket = 'OUT_OF_SCOPE')")
    op.create_check_constraint("ck_pois_indoor_outdoor", "pois",
                               "indoor_outdoor IN ('indoor','outdoor','mixed','unknown')")
    op.create_check_constraint(
        "ck_pois_duration_order", "pois",
        "0 < visit_duration_min AND visit_duration_min <= visit_duration_typical "
        "AND visit_duration_typical <= visit_duration_max")
    op.create_check_constraint(
        "ck_pois_cost_order", "pois",
        "0 <= estimated_cost_min AND estimated_cost_min <= estimated_cost_typical "
        "AND estimated_cost_typical <= estimated_cost_max")
    op.create_index("ix_pois_experience_tags", "pois", ["experience_tags"], postgresql_using="gin")
    op.create_index("ix_pois_mood_tags", "pois", ["mood_tags"], postgresql_using="gin")
    op.create_index("ix_pois_region", "pois", ["region_bucket", "active"])
    op.create_index("ix_pois_search_tsv", "pois", ["search_tsv"], postgresql_using="gin")
    op.create_index("ix_pois_recommendable_quality", "pois", ["recommendable", "quality_score"])
    op.execute("CREATE INDEX IF NOT EXISTS idx_pois_geom ON pois USING gist (geom)")

    op.execute("DELETE FROM poi_opening_hours WHERE close_min <= open_min AND NOT closed_all_day")
    op.create_check_constraint("ck_hours_interval", "poi_opening_hours",
                               "close_min > open_min OR closed_all_day")

    # ---------------------------------------------------------- interactions
    op.alter_column("poi_interactions", "user_id", nullable=True)
    op.add_column("poi_interactions", sa.Column("session_id", sa.String(64)))
    op.add_column("poi_interactions", sa.Column("created_at", sa.DateTime(timezone=True),
                                                server_default=sa.text("now()"),
                                                nullable=False))
    op.execute(f"UPDATE poi_interactions SET action = 'view' "
               f"WHERE action NOT IN {INTERACTION_ACTIONS}")
    op.create_check_constraint("ck_interaction_owner", "poi_interactions",
                               "user_id IS NOT NULL OR session_id IS NOT NULL")
    op.create_check_constraint("ck_interaction_action", "poi_interactions",
                               f"action IN {INTERACTION_ACTIONS}")
    op.create_index("ix_poi_interactions_user_time", "poi_interactions",
                    ["user_id", "created_at"])
    op.create_index("ix_poi_interactions_session_time", "poi_interactions",
                    ["session_id", "created_at"])

    # ------------------------------------------------------------ new tables
    op.create_table(
        "poi_aliases",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("poi_id", sa.Integer(), sa.ForeignKey("pois.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("alias_normalized", sa.Text(), nullable=False),
        sa.Column("source", sa.String(20), nullable=False),
        sa.UniqueConstraint("poi_id", "alias_normalized", name="uq_poi_alias"),
    )
    op.create_index("ix_poi_aliases_trgm", "poi_aliases", ["alias_normalized"],
                    postgresql_using="gin", postgresql_ops={"alias_normalized": "gin_trgm_ops"})

    op.create_table(
        "saved_pois",
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("user.id", ondelete="CASCADE"),
                  primary_key=True),
        sa.Column("poi_id", sa.Integer(), sa.ForeignKey("pois.id", ondelete="CASCADE"),
                  primary_key=True),
        sa.Column("note", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
    )

    op.create_table(
        "poi_embeddings",
        sa.Column("poi_id", sa.Integer(), sa.ForeignKey("pois.id", ondelete="CASCADE"),
                  primary_key=True),
        sa.Column("embedding", Vector(768), nullable=False),
        sa.Column("model", sa.String(80), nullable=False),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.execute("CREATE INDEX ix_poi_embeddings_hnsw ON poi_embeddings "
               "USING hnsw (embedding vector_cosine_ops)")

    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("source_ref", sa.String(60), nullable=False, unique=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("name_normalized", sa.Text(), nullable=False),
        _arr("aliases"),
        sa.Column("place_type", sa.String(20), nullable=False),
        sa.Column("geom", geoalchemy2.types.Geography(geometry_type="POINT", srid=4326,
                                                      spatial_index=False),
                  nullable=False),
        sa.Column("distance_from_center_km", sa.Numeric(7, 3), nullable=False),
        sa.Column("region_bucket", sa.String(20), nullable=False),
        sa.Column("district", sa.String(80)),
        sa.Column("importance", sa.Numeric(4, 3), server_default="0", nullable=False),
    )
    op.create_index("ix_places_name_trgm", "places", ["name_normalized"],
                    postgresql_using="gin", postgresql_ops={"name_normalized": "gin_trgm_ops"})
    op.execute("CREATE INDEX idx_places_geom ON places USING gist (geom)")

    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("source", sa.String(40), nullable=False),
        sa.Column("external_id", sa.String(200), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text()),
        sa.Column("license", sa.String(120), nullable=False),
        sa.Column("doc_type", sa.String(30), server_default="article", nullable=False),
        sa.Column("poi_id", sa.Integer(), sa.ForeignKey("pois.id", ondelete="SET NULL")),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.UniqueConstraint("source", "external_id", name="uq_knowledge_doc"),
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("document_id", sa.Integer(),
                  sa.ForeignKey("knowledge_documents.id", ondelete="CASCADE"), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(768)),
        sa.Column("embedding_model", sa.String(80)),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("tsv", postgresql.TSVECTOR(),
                  sa.Computed("to_tsvector('english', chunk_text)", persisted=True)),
        sa.Column("metadata", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunk_index"),
    )
    op.create_index("ix_knowledge_chunks_tsv", "knowledge_chunks", ["tsv"],
                    postgresql_using="gin")
    op.execute("CREATE INDEX ix_knowledge_chunks_hnsw ON knowledge_chunks "
               "USING hnsw (embedding vector_cosine_ops)")

    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("user.id", ondelete="CASCADE")),
        sa.Column("session_id", sa.String(64)),
        sa.Column("state", postgresql.JSONB(), server_default="{}", nullable=False),
        sa.Column("summary", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_index("ix_conversations_user_id", "conversations", ["user_id"])
    op.create_index("ix_conversations_session_id", "conversations", ["session_id"])
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("conversation_id", sa.UUID(),
                  sa.ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role", sa.String(12), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB()),
        sa.Column("intent", sa.String(40)),
        sa.Column("trace_id", sa.UUID()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_index("ix_messages_conversation", "messages", ["conversation_id", "id"])

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("conversation_id", sa.UUID(),
                  sa.ForeignKey("conversations.id", ondelete="CASCADE")),
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("user.id", ondelete="CASCADE")),
        sa.Column("intent", sa.String(40)),
        sa.Column("intent_confidence", sa.Numeric(4, 3)),
        sa.Column("intent_source", sa.String(10)),
        sa.Column("workflow", sa.String(40)),
        sa.Column("states", postgresql.JSONB(), server_default="[]", nullable=False),
        sa.Column("status", sa.String(20), server_default="running", nullable=False),
        sa.Column("error_code", sa.String(40)),
        sa.Column("tool_call_count", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("llm_call_count", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("ranking_config_version", sa.String(20)),
        sa.Column("latency_ms", sa.Integer()),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_index("ix_agent_runs_started_at", "agent_runs", ["started_at"])
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("run_id", sa.UUID(), sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("tool_name", sa.String(60), nullable=False),
        sa.Column("args_hash", sa.String(64), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("error_code", sa.String(40)),
        sa.Column("latency_ms", sa.Integer()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_index("ix_tool_calls_run_id", "tool_calls", ["run_id"])
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("run_id", sa.UUID(), sa.ForeignKey("agent_runs.id", ondelete="CASCADE")),
        sa.Column("task", sa.String(40), nullable=False),
        sa.Column("model", sa.String(80), nullable=False),
        sa.Column("prompt_version", sa.String(20), nullable=False),
        sa.Column("prompt_hash", sa.String(64), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("error_code", sa.String(40)),
        sa.Column("cached", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("latency_ms", sa.Integer()),
        sa.Column("prompt_tokens", sa.Integer()),
        sa.Column("completion_tokens", sa.Integer()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_index("ix_llm_calls_run_id", "llm_calls", ["run_id"])
    op.create_index("ix_llm_calls_created_at", "llm_calls", ["created_at"])
    op.create_table(
        "feedback",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("user_id", sa.UUID(), sa.ForeignKey("user.id", ondelete="CASCADE")),
        sa.Column("session_id", sa.String(64)),
        sa.Column("target_type", sa.String(20), nullable=False),
        sa.Column("target_id", sa.String(80), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.CheckConstraint("rating IN (-1, 0, 1)", name="ck_feedback_rating"),
        sa.CheckConstraint("char_length(coalesce(comment, '')) <= 2000", name="ck_feedback_len"),
        sa.CheckConstraint("target_type IN ('answer','poi','itinerary','recommendation')",
                           name="ck_feedback_target"),
    )
    op.create_index("ix_feedback_target", "feedback", ["target_type", "target_id"])

    # ----------------------------------------------------------- itineraries
    op.add_column("itineraries", sa.Column("session_id", sa.String(64)))
    op.add_column("itineraries", sa.Column("title", sa.Text()))
    op.add_column("itineraries", sa.Column("updated_at", sa.DateTime(timezone=True),
                                           server_default=sa.text("now()")))
    op.create_index("ix_itineraries_session_id", "itineraries", ["session_id"])
    op.execute("UPDATE itineraries SET session_id = 'legacy-unowned' "
               "WHERE user_id IS NULL AND session_id IS NULL")
    op.drop_constraint("ck_itinerary_status", "itineraries", type_="check")
    op.create_check_constraint(
        "ck_itinerary_status", "itineraries",
        "status IN ('draft','saved','active','completed','abandoned')")
    op.create_check_constraint("ck_itinerary_owner", "itineraries",
                               "user_id IS NOT NULL OR session_id IS NOT NULL")

    op.add_column("itinerary_versions", sa.Column("kind", sa.String(10),
                                                  server_default="version", nullable=False))
    op.add_column("itinerary_versions", sa.Column("variant_status", sa.String(10)))
    op.add_column("itinerary_versions", sa.Column(
        "parent_version_id", sa.Integer(), sa.ForeignKey("itinerary_versions.id")))
    op.add_column("itinerary_versions", sa.Column("change_operation", postgresql.JSONB()))
    op.add_column("itinerary_versions", sa.Column("label", sa.Text()))
    op.add_column("itinerary_versions", sa.Column("tripspec_snapshot", postgresql.JSONB()))
    # The rendered itinerary exactly as the user saw it, so history and
    # comparisons replay faithfully even if POI data later changes.
    op.add_column("itinerary_versions", sa.Column("itinerary", postgresql.JSONB()))
    op.alter_column("itinerary_versions", "version_no", nullable=True)
    op.create_check_constraint("ck_version_kind", "itinerary_versions",
                               "kind IN ('version','variant')")
    op.create_check_constraint(
        "ck_version_variant_shape", "itinerary_versions",
        "(kind = 'version' AND version_no IS NOT NULL AND variant_status IS NULL) OR "
        "(kind = 'variant' AND version_no IS NULL AND "
        " variant_status IN ('pending','applied','rejected'))")
    op.execute("UPDATE itineraries i SET current_version_id = NULL WHERE current_version_id "
               "IS NOT NULL AND NOT EXISTS (SELECT 1 FROM itinerary_versions v "
               "WHERE v.id = i.current_version_id)")
    op.create_foreign_key("fk_itinerary_current_version", "itineraries", "itinerary_versions",
                          ["current_version_id"], ["id"], ondelete="SET NULL")

    op.add_column("itinerary_stops", sa.Column("transition_buffer_min", sa.SmallInteger(),
                                               server_default="0", nullable=False))
    op.alter_column("itinerary_stops", "travel_seconds_from_prev", server_default=None)
    op.alter_column("itinerary_stops", "travel_distance_m_from_prev", server_default=None)
    op.alter_column("itinerary_stops", "walk_m_from_prev", server_default=None)
    op.alter_column("itinerary_stops", "leg_cost_inr", server_default=None)
    op.create_check_constraint("ck_stop_times", "itinerary_stops", "depart_min >= arrive_min")


def downgrade() -> None:
    op.drop_constraint("ck_stop_times", "itinerary_stops", type_="check")
    op.drop_column("itinerary_stops", "transition_buffer_min")

    op.drop_constraint("fk_itinerary_current_version", "itineraries", type_="foreignkey")
    op.execute("DELETE FROM itinerary_versions WHERE kind = 'variant'")
    op.drop_constraint("ck_version_variant_shape", "itinerary_versions", type_="check")
    op.drop_constraint("ck_version_kind", "itinerary_versions", type_="check")
    op.alter_column("itinerary_versions", "version_no", nullable=False)
    for col in ("itinerary", "tripspec_snapshot", "label", "change_operation",
                "parent_version_id",
                "variant_status", "kind"):
        op.drop_column("itinerary_versions", col)

    op.drop_constraint("ck_itinerary_owner", "itineraries", type_="check")
    op.drop_constraint("ck_itinerary_status", "itineraries", type_="check")
    op.execute("UPDATE itineraries SET status = 'draft' WHERE status = 'saved'")
    op.create_check_constraint(
        "ck_itinerary_status", "itineraries",
        "status IN ('draft','active','completed','abandoned')")
    op.drop_index("ix_itineraries_session_id", table_name="itineraries")
    for col in ("updated_at", "title", "session_id"):
        op.drop_column("itineraries", col)

    for table in ("feedback", "llm_calls", "tool_calls", "agent_runs", "messages",
                  "conversations", "knowledge_chunks", "knowledge_documents", "places",
                  "poi_embeddings", "saved_pois", "poi_aliases", "user_preferences",
                  "refresh_tokens"):
        op.drop_table(table)

    op.drop_index("ix_poi_interactions_session_time", table_name="poi_interactions")
    op.drop_index("ix_poi_interactions_user_time", table_name="poi_interactions")
    op.drop_constraint("ck_interaction_action", "poi_interactions", type_="check")
    op.drop_constraint("ck_interaction_owner", "poi_interactions", type_="check")
    op.execute("DELETE FROM poi_interactions WHERE user_id IS NULL")
    op.drop_column("poi_interactions", "created_at")
    op.drop_column("poi_interactions", "session_id")
    op.alter_column("poi_interactions", "user_id", nullable=False)

    op.drop_constraint("ck_hours_interval", "poi_opening_hours", type_="check")

    # Restore the v1 POI columns from their v2 replacements.
    op.add_column("pois", sa.Column("visit_minutes", sa.Integer()))
    op.add_column("pois", sa.Column("cost_estimate_inr", sa.Integer()))
    op.add_column("pois", sa.Column("cost_basis", sa.String(20)))
    op.add_column("pois", sa.Column("indoor", sa.Boolean()))
    op.add_column("pois", sa.Column("weather_flags", postgresql.JSONB(),
                                    server_default="{}", nullable=False))
    op.add_column("pois", sa.Column("area", sa.String(80)))
    op.execute("""
        UPDATE pois SET visit_minutes = visit_duration_typical,
            cost_estimate_inr = CASE WHEN cost_confidence <> 'category_default'
                                     THEN estimated_cost_typical END,
            indoor = CASE indoor_outdoor WHEN 'indoor' THEN true
                                         WHEN 'outdoor' THEN false END,
            area = left(locality, 80)
    """)
    for name in ("ix_pois_recommendable_quality", "ix_pois_search_tsv", "ix_pois_region",
                 "ix_pois_mood_tags", "ix_pois_experience_tags"):
        op.drop_index(name, table_name="pois")
    for name in ("ck_pois_cost_order", "ck_pois_duration_order", "ck_pois_indoor_outdoor",
                 "ck_pois_region", "ck_pois_distance", "ck_pois_quality"):
        op.drop_constraint(name, "pois", type_="check")
    op.drop_constraint("uq_pois_slug", "pois", type_="unique")
    for col in ("search_tsv", "updated_at", "created_at", "search_text", "source_updated_at",
                "source_license", "source_names", "source_urls", "image_attribution",
                "wikipedia_title", "chain_key", "is_chain", "day_trip_suitable", "short_escape",
                "requires_large_time_block", "recommended_as_primary_destination",
                "group_friendly", "solo_friendly", "couple_friendly", "senior_friendly",
                "kids_friendly", "family_friendly", "recommendable", "data_confidence",
                "cost_confidence", "estimated_cost_max", "estimated_cost_typical",
                "estimated_cost_min", "visit_duration_max", "visit_duration_typical",
                "visit_duration_min", "opening_hours_confidence", "opening_hours_raw",
                "weather_suitability", "indoor_outdoor", "accessibility_tags", "activity_tags",
                "dietary_tags", "food_tags", "mood_tags", "experience_tags", "neighborhood",
                "locality", "district", "region_bucket", "distance_from_center_km",
                "description_source", "short_description", "slug"):
        op.drop_column("pois", col)

    for col in ("is_theme", "cost_max", "cost_min", "visit_max", "visit_min",
                "indoor_outdoor", "group_key"):
        op.drop_column("poi_categories", col)

    op.drop_column("user", "created_at")
    op.drop_column("user", "display_name")
