"""user profile columns

Revision ID: b66d73651873
Revises: 2bb6d252a09d
Create Date: 2026-09-22 10:55:55.876104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b66d73651873'
down_revision: Union[str, Sequence[str], None] = '2bb6d252a09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('home_name', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('home_lat', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('home_lon', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('interests', postgresql.ARRAY(sa.String(length=40)), server_default='{}', nullable=False))
    op.add_column('user', sa.Column('vegetarian', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vegetarian')
    op.drop_column('user', 'interests')
    op.drop_column('user', 'home_lon')
    op.drop_column('user', 'home_lat')
    op.drop_column('user', 'home_name')
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
