"""NQ-012: POI schema

Revision ID: d8ddbda0979e
Revises: 86d61c5ce865
Create Date: 2026-09-03 18:19:46.840169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'd8ddbda0979e'
down_revision: Union[str, Sequence[str], None] = '86d61c5ce865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_categories',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('default_visit_minutes', sa.Integer(), nullable=False),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('weather_sensitive', sa.Boolean(), nullable=False),
    sa.Column('typical_cost_inr', sa.Integer(), nullable=False),
    sa.Column('meal_category', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=60), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_normalized', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('primary_category', sa.SmallInteger(), nullable=False),
    sa.Column('prominence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('prominence_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visit_minutes', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_inr', sa.Integer(), nullable=True),
    sa.Column('cost_basis', sa.String(length=20), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('weather_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wikidata_id', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('curated', sa.Boolean(), nullable=False),
    sa.Column('editorial_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('prominence >= 0 AND prominence <= 1', name='ck_pois_prominence'),
    sa.ForeignKeyConstraint(['primary_category'], ['poi_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_ref', name='uq_pois_source_ref')
    )
    op.create_index('ix_pois_category_active', 'pois', ['primary_category', 'active'], unique=False)
    op.create_index('ix_pois_name_trgm', 'pois', ['name_normalized'], unique=False, postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.create_index('ix_pois_prominence', 'pois', ['prominence'], unique=False)
    op.create_index('ix_pois_tags', 'pois', ['tags'], unique=False, postgresql_using='gin', postgresql_ops={'tags': 'jsonb_path_ops'})
    op.create_table('poi_category_links',
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['poi_categories.id'], ),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poi_id', 'category_id')
    )
    op.create_table('poi_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_poi_interactions_user', 'poi_interactions', ['user_id', 'poi_id'], unique=False)
    op.create_table('poi_opening_hours',
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('open_min', sa.SmallInteger(), nullable=False),
    sa.Column('close_min', sa.SmallInteger(), nullable=False),
    sa.Column('is_24h', sa.Boolean(), nullable=False),
    sa.Column('closed_all_day', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('close_min BETWEEN 0 AND 1440', name='ck_hours_close'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_hours_dow'),
    sa.CheckConstraint('open_min BETWEEN 0 AND 1440', name='ck_hours_open'),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poi_id', 'day_of_week', 'open_min')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poi_opening_hours')
    op.drop_index('ix_poi_interactions_user', table_name='poi_interactions')
    op.drop_table('poi_interactions')
    op.drop_table('poi_category_links')
    op.drop_index('ix_pois_tags', table_name='pois', postgresql_using='gin', postgresql_ops={'tags': 'jsonb_path_ops'})
    op.drop_index('ix_pois_prominence', table_name='pois')
    op.drop_index('ix_pois_name_trgm', table_name='pois', postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.drop_index('ix_pois_category_active', table_name='pois')
    op.drop_table('pois')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('poi_categories')
    # ### end Alembic commands ###
