services:
  db:
    build:
      context: ./database
    container_name: navigiq_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - navigiq_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    container_name: navigiq_backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ../backend:/app
    env_file:
      - ../backend/.env.example
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: navigiq_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  navigiq_postgres_data:
