services:
  db:
    build:
      context: ./database
    container_name: navigiq_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - navigiq_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    container_name: navigiq_backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ../backend:/app
    env_file:
      - ../backend/.env.example
    depends_on:
      - db

volumes:
  navigiq_postgres_data:
